### ISSUE TITLE
Backoffice fails to load if missing trailing `/`

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/nginx#1]
When loading Backoffice with a missing trailing `/` the initial resource loads due to the [current nginx config](https://github.com/PlaceOS/nginx/blob/4d89b5f88cddba0acdb2827bf565cf523e9469e5/config/nginx.conf#L59) however other required assets do not.

![mail](https://user-images.githubusercontent.com/843652/100992207-a177fe80-359f-11eb-8680-8621e31c4085.png)

**Comment by w-le** [comment]
based on previous experience I believe ce5f283 will resolve that issue, though strangely when I tested with the existing config that issue actually didn't occur

**Comment by w-le** [comment]
Since I wasn't able reproduce the issue (super weird, `/backoffice` just worked even on master branch, and incognito), are you able to test on `fix/static_locations` and confirm if that resolve the issue @KimBurgess ?

**Comment by KimBurgess** [comment]
No dice. With that removed it falls through to here: https://github.com/PlaceOS/nginx/blob/ce5f283c9e110aa309d9816336e5532d2bac2aa4/config/nginx.conf#L44

This results in a 301, but _only_ works if the server is running on port 443.
```
> https --verify=no localhost:8443/backoffice
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Content-Length: 175
Content-Type: text/html
Date: Fri, 04 Dec 2020 04:30:48 GMT
Location: https://localhost/backoffice/
Server: openresty/1.19.3.1

<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>openresty/1.19.3.1</center>
</body>
</html>
```

**Comment by KimBurgess** [comment]
@w-le are you still looking at this one? Dropping myself as an assignee so that we don't have multiple people all not looking at it at once. Feel free to pipe back my way if required though.

**Comment by w-le** [comment]
yep i'll reproduce the issue and have a fiddle this week
