### ISSUE TITLE
Allow CORS for PlaceOS Portal by default

### ISSUE THREAD

**Issue by w-le** [PlaceOS/nginx#22]
@vinnyo can explain what the requirements would be

**Comment by vinnyo** [comment]
Support for placeos instances to whitelist portal domains: `portal.placeos.run' and `portal-dev.placeos.run`

This was the config that Ollie had used previously. `https://gist.github.com/OllieMoylette/ff848c7a5176dd383c95464a60582c2b#file-gistfile1-txt-L172`

Generally it was whitelisting portal domains for '/api/', `/api/files/` and `/auth/` route paths.
