### ISSUE TITLE
Contents of `.git` directory exposed

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/nginx#3]
**Describe the bug**
Interface repositories served with the default config enable retrieval of the contents of the `.git` directory. While directory listing is not enabled, this does allow for the retrieval of specific files resulting in information disclosure for frontend assets.

**To Reproduce**
Query `<domain>/<interface>/.git/HEAD` (or other well known file).

**Expected behavior**
The server should response with a HTTP 403, or potentially a 404.

**Additional context**
Addition protection should potentially be added to `PlaceOS/frontends` to seperate file system locations for cached deployment assets from the upstream source and what is being served, however protection here makes sense also.

**Comment by viv-4** [comment]
Oh your way is better, all hidden dirs
